### ISSUE TITLE
Add support for UWP

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/Bxf#4]

**Comment by xperiandri** [comment]
Does your `CategoryAttribute` created yourself works in Visual Studio and Blend?

**Comment by rockfordlhotka** [comment]
The `CategoryAttribute` exists in some versions of .NET. It has its origins in .NET 1.0 and the Windows Forms designer. That designer uses the attribute to organize properties in the Properties window in Visual Studio. That is still true today.

When I ported the code to support other platforms that _don't_ have that attribute I had a choice of either putting compiler directives throughout my code, or creating a replacement for the attribute so the code continues to compile unchanged. I chose to create a replacement for the attribute.

On the platforms where the replacement is used, no, Visual Studio won't honor the attribute because it isn't a Microsoft attribute. But if you are working in Windows Forms, Web Forms, and maybe WPF then the attribute is the original Microsoft attribute and Visual Studio uses it to organize the Properties window.
